.PHONY: all test lint

all: build

build:
	@echo "Building..."
	go build ./...

test:
	go test -race ./...
	cd cerr && go test -race ./...
	cd gerr && go test -race ./...
	cd herr && go test -race ./...

lint:
	@command -v golangci-lint >/dev/null 2>&1 || { \
		echo "golangci-lint is not installed"; \
		exit 1; \
	}
	golangci-lint run ./...
	cd cerr && golangci-lint run ./...
	cd gerr && golangci-lint run ./...
	cd herr && golangci-lint run ./...
	cd examples && golangci-lint run ./...
